### ISSUE TITLE
Generating tiles fails on part 1 being solved and part 2 not being solved

### ISSUE THREAD

**Issue by cuteredpwnda** [LiquidFun/adventofcode#1]
First of all: Thanks for the cool visualization!

Generating the tiles for my 2021 attempt at AoC bugs out with `line 229, in format_time h, m, s = time.split(":") ValueError: not enough values to unpack (expected 3, got 1)` generating the 3rd tile of 2021.
I suppose this has to do with me not finishing with 2 stars and the leaderbord showing the `- - -` pattern?

Can anyone reproduce this error?

I'll try to resolve the issue and create a pull request.

**Comment by LiquidFun** [comment]
Ah, yeah, I always solved both parts so I never tried with only part 1 solved. Thanks for the pull request, looks good!
