### ISSUE TITLE
AssertionError: Found no leaderboard?!

### ISSUE THREAD

**Issue by Zoibderg** [LiquidFun/adventofcode#10]
When attempting to generate tiles I'm met with this lovely AssertionError. I have meticulously scoured the README to try and find any solutions and have yet to find any, though I could easily just be missing something. 

Here is the Traceback:
[traceback.txt](https://github.com/LiquidFun/adventofcode/files/10168956/traceback.txt)

This is also populated in the leaderboard2022.html file:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

Again I'm sure that there is something simple that I'm missing, so I apologize if that the case! Anyway, any help at all would be awesome!

**Comment by Zoibderg** [comment]
Yup, just as I expected; ID10T error. My session cookie had a prefix. After removing that and deleting the leaderboard2022.html file the tiles with generated with no issues.

**Comment by LiquidFun** [comment]
Alright, good to know! I'll see if I can add some more informative error messages in the future.
