### ISSUE TITLE
Creating tiles for manual upload/insertion into a README.

### ISSUE THREAD

**Issue by Rietty** [LiquidFun/adventofcode#11]
Hi! I was hoping you could help, I'm trying to separate out the code for year and the folder structure and all that but having trouble. Would you happen to have a version of this script which will simply scrape and generate the images for a given year based off the leaderboard, with a language we can manually specify instead of reading/trying to get it from the source code and all that? I just want to be able to generate the images and make my readme look nice and these are cute. My code/directory is not set up remotely close to how this one seems to be structured and I would appreciate some pointers on how to run this script completely standalone.

**Comment by LiquidFun** [comment]
Hey, yeah this is not too hard, the first function in the `create_aoc_tiles.py` script is exactly meant for that:

https://github.com/LiquidFun/adventofcode/blob/daf8aae2ec42603f609b7014d27b79c5a9b5fd8c/AoCTiles/create_aoc_tiles.py#L68-L107

So:

1. Put the AoCTiles folder in your repository
2. Install requirements: `pip install requirements.txt`
3. Change that function `get_solution_paths_dict_for_years()` to this (I have modified it so it works for your structure, it shouldn't need to be changed):
```py
def get_solution_paths_dict_for_years() -> dict[int, dict[int, list[str]]]:
    solution_paths_dict: dict[int, dict[int, list[str]]] = {}

    year = 2022
    solution_paths_dict[year] = {}

    for solution_path in AOC_DIR.rglob("src/solutions/day*.rs"):
        day = find_first_number(solution_path.name)
        solution_paths_dict[year][day] = [solution_path.relative_to(AOC_DIR).as_posix()]
    return solution_paths_dict
```
4. Add `<!-- AOC TILES BEGIN -->` and `<!-- AOC TILES END -->` to your README.md
5. Put your session cookie in the root folder of the repository into the file `session.cookie` (do NOT commit this)
6. Commit the files in `Media` and the README.md. Commiting the AoCTiles folder is optional.
7. (Optional, if you want to add the images on each commit: add my `.pre-commit-config.yaml` to your repository and install with `pre-commit install`)

**Comment by Rietty** [comment]
Thank you so much! I really appreciate you taking the time to help me with this. I will try it out!

**Comment by Rietty** [comment]
Seems as if the the line: `solution_paths_dict[year][day] = solution_path.relative_to(AOC_DIR).as_posix()` has some syntax error or something? Does this need to be run on a linux environment of some sort?

**Comment by LiquidFun** [comment]
Can you add the error here?

**Comment by Rietty** [comment]
Hi @LiquidFun Apologies. I figured out the issue. I was running Python 3.8, it needed Python 3.10 or newer, doing so resolved all issues. Thank you!!!

**Comment by Rietty** [comment]
Oh sorry, apparently I do get a multicolored image with a bunch of file extensions instead of just `.rs` and a singular colour. I think that it is picking up random file extensions outside the solutions folder?

Example: 
![image](https://user-images.githubusercontent.com/35241556/209478595-5565634f-aa9b-4e41-9c9a-a1f6031abce7.png)

**Comment by LiquidFun** [comment]
oops, yeah, my mistake, I forgot that it needs to be a list. The function needs to be like this:

```py
def get_solution_paths_dict_for_years() -> dict[int, dict[int, list[str]]]:
    solution_paths_dict: dict[int, dict[int, list[str]]] = {}

    year = 2022
    solution_paths_dict[year] = {}

    for solution_path in AOC_DIR.rglob("src/solutions/day*.rs"):
        day = find_first_number(solution_path.name)
        solution_paths_dict[year][day] = [solution_path.relative_to(AOC_DIR).as_posix()]
    return solution_paths_dict
```

The only difference is in the second to last line, I added [] around the solution.

**Comment by Rietty** [comment]
Perfect, thank you so much!
