### ISSUE TITLE
Wrong tile generated

### ISSUE THREAD

**Issue by cernezan** [LiquidFun/adventofcode#8]
![Screenshot 2022-12-05 at 20 29 26](https://user-images.githubusercontent.com/57217296/205726156-acb07f8b-f776-493a-a232-6c20ba1c7162.png)
This is how my tile looks after solving day 5 of aoc. Day 1-4 generated correctly, but day 5 somehow didn't. On the aoc website I got 2 stars as seen in the screenshot below. Let me know if I'm doing something wrong.
<img width="66" alt="Screenshot 2022-12-05 at 20 32 38" src="https://user-images.githubusercontent.com/57217296/205726362-ae824cda-27c9-4487-8197-05206cd53763.png">

**Comment by LiquidFun** [comment]
This should be fixed in the newest version. Can you update your version of the script and try again?

**Comment by cernezan** [comment]
Now it works as expected! Thanks!
